In [9]:
import pandas as pd
import numpy as np

names = ['Company', 'CEO', 'MST', 'NGANH_NGHE']
data1 = pd.read_csv('vnr_profit_500_1.csv',names= names,dtype = {'MST':np.str})
# data1['Type'] = 1
data2 = pd.read_csv('vnr_profit_500.csv',names=names ,dtype = {'MST':np.str})
# data2['Type'] = '2'
data2 = data2.drop_duplicates(subset = ['MST'])
data2 = data2.reset_index(drop = True)
data = pd.concat([data1,data2],ignore_index = True)
data = data.drop_duplicates(subset=['MST'])
data = data.reset_index(drop = True)
data

/var/folders/x7/psmldpq556b7kvl0wpx_bx_h0000gn/T/ipykernel_31835/3038757370.py:5: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  data1 = pd.read_csv('vnr_profit_500_1.csv',names= names,dtype = {'MST':np.str})
/var/folders/x7/psmldpq556b7kvl0wpx_bx_h0000gn/T/ipykernel_31835/3038757370.py:7: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  data2 = pd.read_csv('vnr_profit_500.csv',names=names ,dtype = {'MST':np.str})

,Company,CEO,MST,NGANH_NGHE
0,TẬP ĐOÀN VINGROUP - CTCP,Nguyễn Việt Quang,0101245486,Kinh doanh bất động sản
1,CÔNG TY CP ĐẦU TƯ THẾ GIỚI DI ĐỘNG,Trần Kinh Doanh,0306731335,"Bán lẻ điện tử, điện lạnh, viễn thông, công ng..."
2,CÔNG TY CP TẬP ĐOÀN VÀNG BẠC ĐÁ QUÝ DOJI,Đỗ Minh Đức,0100365621,"Bán lẻ vàng, bạc và kim loại quý khác"
3,CÔNG TY CP TẬP ĐOÀN HÒA PHÁT,Nguyễn Việt Thắng,0900189284,"Sản xuất, gia công kim loại, sắt thép, kim khí…"
4,CÔNG TY CP TẬP ĐOÀN MASAN,Danny Lê,0303576603,Dịch vụ khác
...,...,...,...,...
691,CÔNG TY TNHH BACONCO,"Siquet, Pierre Louis Bernard",3500101065,"Sản xuất, kinh doanh phân bón, thuốc trừ sâu"
692,CÔNG TY CP CÔNG NGHIỆP NHỰA PHÚ LÂM,Huang Cheng Hung,0200109445,"Sản xuất, kinh doanh nhựa và sản phẩm từ nhựa"
693,CÔNG TY TNHH LIÊN DOANH SẢN XUẤT ÔTÔ NGÔI SAO,Ryujiro Kobashi,3700229030,"Sản xuất, kinh doanh ô tô, xe máy, xe có động ..."
694,TỔNG CÔNG TY GIẤY VIỆT NAM,.,2600357502,"Sản xuất, kinh doanh giấy và các sản phẩm từ giấy"
695,CÔNG TY CP HANACANS,Hidetaka Makabe,2300372796,"Sản xuất, kinh doanh máy móc, sản phẩm cơ khí ..."

In [10]:
import pandas as pd
import numpy as np
data3 = pd.read_csv('Result_total_vietstock.csv',dtype = {'mst': np.str})
data3 = data3.dropna(subset = ['mst'])
data3['mst'] = data3['mst'].astype('string')
data3['mst'] = data3['mst'].str.strip()
data3['mst'] = data3['mst'].str.replace(' ','')
data3['mst'] = data3['mst'].str[:10]
data3['mst'] = data3['mst'].str.replace('.','')
# data3['mst'] = data3['mst'].str.replace('','')
data3['mst'] = data3['mst'].apply(lambda x: x if len(x) == 10 else '0'+ x)
data3.loc[data3['doanh_thu_2020'].isna() == True].count()
data3

/var/folders/x7/psmldpq556b7kvl0wpx_bx_h0000gn/T/ipykernel_31835/113803849.py:3: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  data3 = pd.read_csv('Result_total_vietstock.csv',dtype = {'mst': np.str})
/var/folders/x7/psmldpq556b7kvl0wpx_bx_h0000gn/T/ipykernel_31835/113803849.py:9: FutureWarning: The default value of regex will change from True to False in a future version. In addition, single character regular expressions will *not* be treated as literal strings when regex=True.
  data3['mst'] = data3['mst'].str.replace('.','')

,Unnamed: 0,mck,ten_cong_ty,mst,cong_ty_con,doanh_thu_2020,doanh_thu_2021
0,0,DTE,CTCP Đầu tư Năng lượng Đại Trường Thành Holdings,0313939535,"CTCP Đầu tư Thủy điện Miền Trung Việt Nam, CTC...","96,066","210,592"
1,1,DTG,CTCP Dược phẩm Tipharco,1200100557,NaN,"244,747","203,146"
2,2,DTH,CTCP Dược Vật tư Y Tế Thanh Hóa,2800231984,Công ty TNHH MTV Dược Thanh Hóa - Hùa Phăn,"533,597","505,216"
3,3,DTI,CTCP Đầu tư Đức Trung,0301466299,Cty TNHH Hợp tác đầu Tư An Bình Long Xuyên,"6,795","58,184"
4,4,DTK,Tổng Công ty Điện lực TKV - CTCP,0104297034,"CTCP Than - Điện Nông Sơn - TKV, CTCP Nhiệt đi...","12,768,778","13,059,307"
...,...,...,...,...,...,...,...
1520,1520,KTC,CTCP Thương mại Kiên Giang,1700523208,"CTCP Thương mại Dịch vụ Kiên Giang, Công ty TN...","5,717,954","5,675,011"
1521,1521,KTL,CTCP Kim Khí Thăng Long,0100100618,Công ty TNHH Phụ tùng Xe máy - Ô tô Goshi Thăn...,"935,718","948,850"
1522,1522,KTS,CTCP Đường Kon Tum,6100228104,NaN,"153,196","248,218"
1523,1523,KTT,CTCP Tập đoàn Đầu tư KTT,0600324084,CT TNHH MTV tư vấn xây lắp điện Thiên Trường,"94,734","453,773"
1524,1524,KVC,CTCP Sản xuất Xuất nhập khẩu Inox Kim Vĩ,4103010382,NaN,"325,795","190,197"

In [11]:
d2020 = dict(zip(data3.mst,data3.doanh_thu_2020))
d2021 = dict(zip(data3.mst,data3.doanh_thu_2021))
data['doanh_thu_2020'] = data['MST'].map(d2020) 
data['doanh_thu_2021'] = data['MST'].map(d2021) 
# data.loc[data['doanh_thu_2020'].isna() == True]
# data.to_csv('VNR500_doanh_thu.csv')
data

,Company,CEO,MST,NGANH_NGHE,doanh_thu_2020,doanh_thu_2021
0,TẬP ĐOÀN VINGROUP - CTCP,Nguyễn Việt Quang,0101245486,Kinh doanh bất động sản,"110,490,033","125,687,870"
1,CÔNG TY CP ĐẦU TƯ THẾ GIỚI DI ĐỘNG,Trần Kinh Doanh,0306731335,"Bán lẻ điện tử, điện lạnh, viễn thông, công ng...","108,546,020","122,958,106"
2,CÔNG TY CP TẬP ĐOÀN VÀNG BẠC ĐÁ QUÝ DOJI,Đỗ Minh Đức,0100365621,"Bán lẻ vàng, bạc và kim loại quý khác",NaN,NaN
3,CÔNG TY CP TẬP ĐOÀN HÒA PHÁT,Nguyễn Việt Thắng,0900189284,"Sản xuất, gia công kim loại, sắt thép, kim khí…","90,118,503","149,679,790"
4,CÔNG TY CP TẬP ĐOÀN MASAN,Danny Lê,0303576603,Dịch vụ khác,NaN,NaN
...,...,...,...,...,...,...
691,CÔNG TY TNHH BACONCO,"Siquet, Pierre Louis Bernard",3500101065,"Sản xuất, kinh doanh phân bón, thuốc trừ sâu",NaN,NaN
692,CÔNG TY CP CÔNG NGHIỆP NHỰA PHÚ LÂM,Huang Cheng Hung,0200109445,"Sản xuất, kinh doanh nhựa và sản phẩm từ nhựa",NaN,NaN
693,CÔNG TY TNHH LIÊN DOANH SẢN XUẤT ÔTÔ NGÔI SAO,Ryujiro Kobashi,3700229030,"Sản xuất, kinh doanh ô tô, xe máy, xe có động ...",NaN,NaN
694,TỔNG CÔNG TY GIẤY VIỆT NAM,.,2600357502,"Sản xuất, kinh doanh giấy và các sản phẩm từ giấy",NaN,NaN
695,CÔNG TY CP HANACANS,Hidetaka Makabe,2300372796,"Sản xuất, kinh doanh máy móc, sản phẩm cơ khí ...",NaN,NaN

In [12]:
import pandas as pd
import numpy as np
tinh = pd.read_csv("VNR_500_tinh_16_11_2022.csv",dtype={'Mã số thuế': np.str})
tinh['Mã số thuế'] = tinh['Mã số thuế'].apply(lambda x: x if len(x) == 10 else '0'+ x)
d2 = dict(zip(tinh['Mã số thuế'],tinh['Tỉnh']))
data['tinh'] = data['MST'].map(d2) 
data
# print(d2)

/var/folders/x7/psmldpq556b7kvl0wpx_bx_h0000gn/T/ipykernel_31835/1841198781.py:3: DeprecationWarning: `np.str` is a deprecated alias for the builtin `str`. To silence this warning, use `str` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.str_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  tinh = pd.read_csv("VNR_500_tinh_16_11_2022.csv",dtype={'Mã số thuế': np.str})

,Company,CEO,MST,NGANH_NGHE,doanh_thu_2020,doanh_thu_2021,tinh
0,TẬP ĐOÀN VINGROUP - CTCP,Nguyễn Việt Quang,0101245486,Kinh doanh bất động sản,"110,490,033","125,687,870",Hà Nội
1,CÔNG TY CP ĐẦU TƯ THẾ GIỚI DI ĐỘNG,Trần Kinh Doanh,0306731335,"Bán lẻ điện tử, điện lạnh, viễn thông, công ng...","108,546,020","122,958,106",Bình Dương
2,CÔNG TY CP TẬP ĐOÀN VÀNG BẠC ĐÁ QUÝ DOJI,Đỗ Minh Đức,0100365621,"Bán lẻ vàng, bạc và kim loại quý khác",NaN,NaN,Hà Nội
3,CÔNG TY CP TẬP ĐOÀN HÒA PHÁT,Nguyễn Việt Thắng,0900189284,"Sản xuất, gia công kim loại, sắt thép, kim khí…","90,118,503","149,679,790",Hưng Yên
4,CÔNG TY CP TẬP ĐOÀN MASAN,Danny Lê,0303576603,Dịch vụ khác,NaN,NaN,TP Hồ Chí Minh
...,...,...,...,...,...,...,...
691,CÔNG TY TNHH BACONCO,"Siquet, Pierre Louis Bernard",3500101065,"Sản xuất, kinh doanh phân bón, thuốc trừ sâu",NaN,NaN,Bà Rịa - Vũng Tàu
692,CÔNG TY CP CÔNG NGHIỆP NHỰA PHÚ LÂM,Huang Cheng Hung,0200109445,"Sản xuất, kinh doanh nhựa và sản phẩm từ nhựa",NaN,NaN,Hải Phòng
693,CÔNG TY TNHH LIÊN DOANH SẢN XUẤT ÔTÔ NGÔI SAO,Ryujiro Kobashi,3700229030,"Sản xuất, kinh doanh ô tô, xe máy, xe có động ...",NaN,NaN,Bình Dương
694,TỔNG CÔNG TY GIẤY VIỆT NAM,.,2600357502,"Sản xuất, kinh doanh giấy và các sản phẩm từ giấy",NaN,NaN,Hà Nội
695,CÔNG TY CP HANACANS,Hidetaka Makabe,2300372796,"Sản xuất, kinh doanh máy móc, sản phẩm cơ khí ...",NaN,NaN,Bắc Ninh

In [13]:
# data.to_csv('VNR500_16_11.csv',index=False)